name: Deploy to dev
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
            node-version: '10.x'
      - uses: actions/checkout@master
      - name: Build project files
        run: |
          npm install
          npm run build

      - name: Deploy to s3
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: us-east-1
            AWS_S3_BUCKET: tools-app-dev
        run:
          aws s3 cp dist s3://$AWS_S3_BUCKET --region us-east-1 --recursive
